/**
 * @ Author: Mo David
 * @ Create Time: 2024-06-14 21:53:19
 * @ Modified time: 2024-07-01 02:24:52
 * @ Description:
 * 
 * This file holds all the Python scripts our program will be running.
 */

import { ClientPyodide } from "./client.pyodide";

export const ClientPython = (function() {
  
  const _ = {};

  // Some default dependencies we import if they haven't been defined
  const _dependencies = `
    try:
      pickle
    except:
      import pickle

    try:
      pd
    except:
      import pandas as pd

    try:
      json
    except:
      import json

    try:
      np
    except:
      import numpy as np
  `;

  // Defines some structures and functions we can use for manipulating our data
  const _dfs = `
    class DF:
      '''
      This class defines a wrapper around dataframe instances.
      '''

      def __init__(self, dataframe, logs, error):
        '''
        Initializes the dataframe wrapper.
        '''
        self.__dataframe = dataframe
        self.__logs = logs
        self.__error = error

      def getDf(self):
        '''
        Retrieves the dataframe stored by the wrapper.
        '''
        return self.__dataframe

      def getLogs(self):
        '''
        Retrieves the complete set of logs generated by the wrapper.
        '''
        return self.__logs

      def getError(self):
        '''
        Retrieves the first error encountered in the chain.
        '''
        return self.__error

      def map(self, f):
        '''
        This function maps the dataframe to its new value using the given callback.
        If the dataframe is invalid, we don't bother executing the function.
        '''

        # The dataframe was invalid
        if self.__dataframe is None:

          # Define the log first
          log = '({}) Failed to apply {}.'.format(len(self.__logs), f.__name__)

          # Return an empty wrapper
          return DF(None, self.__logs + [ log ], self.__error)

        # Evaluate the result and error, if any
        result, log, error, *_ = f(self.__dataframe) + (None, None)

        # If no log was given, define it here
        # Otherwise, format it properly
        if log:
          log = '({}) {}'.format(len(self.__logs), log) 
        else:
          log = '({}) Applied {}.'.format(len(self.__logs), f.__name__)

        # If no error was given
        error = error or self.__error or None

        # Map the original value elsewhere
        return DF(result, self.__logs + [ log ], error)

      @staticmethod
      def of(dataframe):
        '''
        This function creates an instance of the wrapper class.
        It provides the defaults of the other parameters.
        '''
        return DF(dataframe, [], None)
  `;

  /**
   * Requests for particular data from Pyodide.
   * Note that we do this by specifying the variable names of the data we want within Pyodide.
   * 
   * @param   { object }    data  The names of the data we want from Pyodide. 
   * @return  { Promise }         A promise for the requested data.
   */
  _.requestData = function(data=[]) {

    // Create a script to return the data
    const string = data.map(key => `'${key}': ${key}`).join(',\n');
    const script = `
      out = {
        ${string}
      }

      print(out)

      json.dumps(out)
    `;

    // Return a promise for the requested data
    // Convert the final data into a JS-readable object
    return _.runScript(script, data => JSON.parse(data));
  }

  /**
   * Defines the given variables in the Python namespace.
   * 
   * @param   { object }  data  The variables to define within the namespace.
   */
  _.sendData = function(data={}) {
    ClientPyodide.processSetContext(data);
  }

  /**
   * Runs a custom Python script.
   * 
   * @param   { string }    script    The script to run. 
   * @param   { function }  callback  An optional callback to deal with the data.
   * @return  { Promise }             A promise for the execution of the script. 
   */
  _.runScript = function(script, callback=d=>d) {

    // Execute the script
    return ClientPyodide.processRun(script, {}, callback)
  }

  return {
    ..._,
  }
})();

